# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 06:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(verbose_name=datetime.datetime(2017, 4, 7, 6, 52, 29, 544000, tzinfo=utc)),
        ),
    ]
